version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - data:/var/lib/postgress/data